export interface MovieList {
  VODs: Movie[];
}

export interface Movie {
  ID: string;
  name: string;

  introduce?: string;

}


// Generated by https://quicktype.io

export interface MovieDetailsResponce {
  result: Result;
  VODDetail: MovieDetails;
}

export interface MovieDetails {
  rating: ProduceZone;
  userScore: string;
  produceDate: string;
  isSubscribed: string;
  ID: string;
  scoreTimes: string;
  contentType: string;
  likes: string;
  bookmark: Bookmark;
  name: string;
  subjectIDs: string[];
  code: string;
  isLike: string;
  mediaFiles: MediaFile[];
  averageScore: string;
  produceZones: ProduceZone[];
  genres: Genre[];
  castRoles: CastRole[];
  introduce: string;
  produceZone: ProduceZone;
  picture: VODDetailPicture;
  VODType: string;
}

export interface Bookmark {
  itemID: string;
  rangeTime: string;
  subContentID: string;
  updateTime: string;
  bookmarkType: string;
}

export interface CastRole {
  casts: Cast[];
  roleType: string;
}

export interface Cast {
  extensionFields: any[];
  castID: string;
  castCode: string;
  picture: CastPicture;
  castName: string;
}

export interface CastPicture {
  hcsSlaveAddrs: any[];
  icons: string[];
  extensionFields: any[];
  others: any[];
}

export interface Genre {
  genreID: string;
  genreType: string;
  genreName: string;
}

export interface MediaFile {
  preview: string;
  isDownload: string;
  code: string;
  customFields: any[];
  maxBitrate: string;
  bitrate: string;
  elapseTime: string;
  multiBitrates: string[];
  extensionFields: any[];
  formatOf3D: string;
  encrypt: string;
  uploadType: string;
  definition: string;
  ID: string;
  dimension: string;
  videoCodec: string;
  CGMSA: string;
  fps: string;
  macrovision: string;
  supportTerminals: any[];
  fileSize: string;
  analogOutputEnable: string;
  HDCPEnable: string;
  fileFormat: string;
}

export interface VODDetailPicture {
  hcsSlaveAddrs: any[];
  posters: string[];
  extensionFields: any[];
  backgrounds: string[];
  others: any[];
}

export interface ProduceZone {
  name: string;
  ID: string;
}

export interface Result {
  retMsg: string;
  retCode: string;
}
